terraform {
  required_providers {
    ibm = {
      source  = "IBM-Cloud/ibm"
      version = "~> 1.39.0"
    }
    local = {
      source = "hashicorp/local"
    }
    template = {
      source = "hashicorp/template"
    }
  }
}

# Configure the IBM Provider. This is targeting Sydney, Australia region
provider "ibm" {
  region = "ap-aud"
}

# Create HPVS instance
resource "ibm_resource_instance" "hpvs" {
  name              = "TEST-HPVS-TERRAFORM"
  service           = "hpvs"

  # Choosing "free/lite-s" for this test. The other valid plans are:
  # "entry", "small", "medium"
  # See https://cloud.ibm.com/catalog/services/hyper-protect-virtual-server
  plan              = "lite-s"

  # Chose where you want the instance provisioned. This is targeting Sydney
  location          = "syd01"

  # Optional timeout
  timeouts {
    create = "15m"
    update = "15m"
    delete = "15m"
  }

  # HPVS specific params.
  # After the instance is provisioned, ssh access works only with the private
  # key that is associated with the public key given here.
  # The public has been generated by `ssh-keygen`
  parameters = {
    sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCUBu50TDZR/2t9REs4UkWXAAHBR5VVew+Q/I5PAgmkwf/M9PriN30CH76i11Ki1JsfmHxJu9N2qus9DzziV/PNAwQgwK9itypmfhSbT2cXMcT4MqjjZowXpIBhy1gLf36A+0lDTuRgV6ZBOlBLLRnHbp70IQpVxXYkB0oYY5cH7PuHAiTWcYyscaMcorMp3QnJSJqFP1x4KPEbQ589yQqOtLjcnKWA9YT/qvv+aHV1q12kgbudEX7siZ3HJ3P7Iy8XYIvEyxP5aKGQ71EYap/inkMeszKSLE1f3wGdXwaNEq5bU+n5JLvdrTahDjCZcMyBqyyhvKlTCA2P/7EF4JqHUoIaoQvWPbCBymAAe/2zpDXUQRPSRTRvHBErFLD3Hl6pZB7UQqW/K9Tgq/PXrO8sdRFhVZ1PpH4SGCRr1iQrP/hhg2Gq8eZTq/8yPiBLTxRk4fnwmvmSXQ41Bc5miEABfSdzpm6f214O4XbcT/5lagVuy64xUzvhsXvMd93miOk= vishwa@vishwanathas-MacBook-Pro.local"
 }
}
